# Generated by Django 4.1.8 on 2023-06-13 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0167_module_status'),
        ('netbox_barcode', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='barcode_list', to='dcim.device')),
            ],
            options={
                'verbose_name': 'Barcode Device List',
                'verbose_name_plural': 'Barcode Device Lists',
            },
        ),
    ]
